### ISSUE TITLE
Feil lenker

### ISSUE THREAD

**Issue by hansfn** [obtitus/ssr2_to_osm_data#1]
Hei

På https://obtitus.github.io/ssr2_to_osm_data/ så er lenker til osm og log filer feil - mappen "ssr2_to_osm_data" er duplisert. Eksempel: https://obtitus.github.io/ssr2_to_osm_data/ssr2_to_osm_data/data/0101/0101.osm

**Comment by obtitus** [comment]
Vopsy. fikset nå.
